'use client';

import React, { useState } from 'react';
import {
  Box,
  Typography,
  TextField,
  Button,
  Card,
  CardContent,
  Paper,
  Avatar,
  Chip,
  IconButton,
  Divider,
  Grid,
} from '@mui/material';
import { CollaborationSession, Message } from '@/types';
import {
  mockSessions,
  addMessageToSession,
  createSession,
} from '@/lib/mockData/mockCollaborationData';
import PersonIcon from '@mui/icons-material/Person';
import SmartToyIcon from '@mui/icons-material/SmartToy';
import SendIcon from '@mui/icons-material/Send';
import ThumbUpIcon from '@mui/icons-material/ThumbUp';
import ThumbDownIcon from '@mui/icons-material/ThumbDown';
import AddIcon from '@mui/icons-material/Add';

export default function CollaborationInterface() {
  const [sessions, setSessions] = useState<CollaborationSession[]>(mockSessions);
  const [activeSessionId, setActiveSessionId] = useState<string | null>(
    sessions.length > 0 ? sessions[0].id : null
  );
  const [messageInput, setMessageInput] = useState('');

  const activeSession = sessions.find((s) => s.id === activeSessionId);

  const handleSendMessage = () => {
    if (!messageInput.trim() || !activeSessionId) return;

    const newMessage = addMessageToSession(activeSessionId, 'user', messageInput);
    if (newMessage) {
      setSessions([...sessions]);
      setMessageInput('');

      // Simulate AI response
      setTimeout(() => {
        const aiResponse = addMessageToSession(
          activeSessionId,
          'assistant',
          `This is a mock AI response to: "${newMessage.content}". In a real implementation, this would be generated by the AI service.`
        );
        if (aiResponse) {
          setSessions([...sessions]);
        }
      }, 1000);
    }
  };

  const handleCreateSession = () => {
    const newSession = createSession('user-1');
    setSessions([newSession, ...sessions]);
    setActiveSessionId(newSession.id);
  };

  const handleFeedback = (messageId: string, feedback: 'positive' | 'negative') => {
    if (!activeSession) return;

    const message = activeSession.messages.find((m) => m.id === messageId);
    if (message) {
      message.feedback = feedback;
      setSessions([...sessions]);
    }
  };

  return (
    <Box>
      <Box sx={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', mb: 3 }}>
        <Box>
          <Typography variant="h4" component="h1" gutterBottom>
            Human-AI Collaboration
          </Typography>
          <Typography variant="body1" color="text.secondary">
            Interactive interfaces for collaborative AI interactions
          </Typography>
        </Box>
        <Button
          variant="contained"
          startIcon={<AddIcon />}
          onClick={handleCreateSession}
        >
          New Session
        </Button>
      </Box>

      <Grid container spacing={3}>
        <Grid size={{ xs: 12, md: 3 }}>
          <Paper sx={{ p: 2 }}>
            <Typography variant="h6" gutterBottom>
              Sessions
            </Typography>
            {sessions.map((session) => (
              <Card
                key={session.id}
                sx={{
                  mb: 1,
                  cursor: 'pointer',
                  backgroundColor:
                    activeSessionId === session.id ? 'action.selected' : 'background.paper',
                }}
                onClick={() => setActiveSessionId(session.id)}
              >
                <CardContent sx={{ p: 2, '&:last-child': { pb: 2 } }}>
                  <Typography variant="subtitle2" noWrap>
                    Session {session.id.split('-')[1]}
                  </Typography>
                  <Typography variant="caption" color="text.secondary">
                    {session.messages.length} messages
                  </Typography>
                  <Chip
                    label={session.status}
                    size="small"
                    sx={{ mt: 1 }}
                    color={session.status === 'active' ? 'primary' : 'default'}
                  />
                </CardContent>
              </Card>
            ))}
          </Paper>
        </Grid>

        <Grid size={{ xs: 12, md: 9 }}>
          {activeSession ? (
            <Paper sx={{ height: '70vh', display: 'flex', flexDirection: 'column' }}>
              <Box sx={{ p: 2, borderBottom: 1, borderColor: 'divider' }}>
                <Typography variant="h6">
                  Session {activeSession.id.split('-')[1]}
                </Typography>
              </Box>
              <Box
                sx={{
                  flexGrow: 1,
                  overflow: 'auto',
                  p: 2,
                  display: 'flex',
                  flexDirection: 'column',
                  gap: 2,
                }}
              >
                {activeSession.messages.map((message) => (
                  <Box
                    key={message.id}
                    sx={{
                      display: 'flex',
                      gap: 2,
                      justifyContent: message.role === 'user' ? 'flex-end' : 'flex-start',
                    }}
                  >
                    {message.role === 'assistant' && (
                      <Avatar sx={{ bgcolor: 'primary.main' }}>
                        <SmartToyIcon />
                      </Avatar>
                    )}
                    <Card
                      sx={{
                        maxWidth: '70%',
                        bgcolor:
                          message.role === 'user'
                            ? 'primary.main'
                            : 'background.default',
                        color:
                          message.role === 'user'
                            ? 'primary.contrastText'
                            : 'text.primary',
                      }}
                    >
                      <CardContent sx={{ p: 2, '&:last-child': { pb: 2 } }}>
                        <Typography variant="body1">{message.content}</Typography>
                        <Typography variant="caption" sx={{ opacity: 0.7, display: 'block', mt: 1 }}>
                          {new Date(message.timestamp).toLocaleTimeString()}
                        </Typography>
                        {message.role === 'assistant' && (
                          <Box sx={{ mt: 1, display: 'flex', gap: 1 }}>
                            <IconButton
                              size="small"
                              onClick={() => handleFeedback(message.id, 'positive')}
                              color={message.feedback === 'positive' ? 'primary' : 'default'}
                            >
                              <ThumbUpIcon fontSize="small" />
                            </IconButton>
                            <IconButton
                              size="small"
                              onClick={() => handleFeedback(message.id, 'negative')}
                              color={message.feedback === 'negative' ? 'error' : 'default'}
                            >
                              <ThumbDownIcon fontSize="small" />
                            </IconButton>
                          </Box>
                        )}
                      </CardContent>
                    </Card>
                    {message.role === 'user' && (
                      <Avatar sx={{ bgcolor: 'secondary.main' }}>
                        <PersonIcon />
                      </Avatar>
                    )}
                  </Box>
                ))}
              </Box>
              <Divider />
              <Box sx={{ p: 2, display: 'flex', gap: 2 }}>
                <TextField
                  fullWidth
                  multiline
                  maxRows={4}
                  placeholder="Type your message..."
                  value={messageInput}
                  onChange={(e) => setMessageInput(e.target.value)}
                  onKeyPress={(e) => {
                    if (e.key === 'Enter' && !e.shiftKey) {
                      e.preventDefault();
                      handleSendMessage();
                    }
                  }}
                />
                <Button
                  variant="contained"
                  endIcon={<SendIcon />}
                  onClick={handleSendMessage}
                  disabled={!messageInput.trim()}
                >
                  Send
                </Button>
              </Box>
            </Paper>
          ) : (
            <Paper sx={{ p: 4, textAlign: 'center' }}>
              <Typography variant="h6" color="text.secondary">
                No active session. Create a new session to start collaborating.
              </Typography>
            </Paper>
          )}
        </Grid>
      </Grid>
    </Box>
  );
}
